on:
    pull_request:
    push:
      branches:
        - master 
  
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
                fetch-depth: 0

          - name: setup-zig
            uses: mlugg/setup-zig@v1
            with:
                version: 0.15.0-dev.460+f4e9846bc
                
          - name: build
            run: zig build

          - name: test
            run: zig build test --summary all     