on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user

      - name: Build
        run: zig build

      - name: Unit Tests
        run: zig build test --summary all

      - name: E2E Tests
        run: |
          python3 tools/test.py
